Readme changes and update to BuildStrategies (#27)
* Renaming example to a standalone directory.

* Renaming buildpacks to a dedicated folder.

* Organizing imports.

* buildpacks-v3 strategy

* s2i strategy

* Formatting and adding new links.

* Renaming file and directory.

* Updating links.

* Updating strategies.

* Updating Kaniko strategy.

* Kaniko link.

* Updating `buildah` strategy.

* Using pre-defined builder images.

* Updating Build examples.

* Updating examples in primary README.

* Buildpacks Build Strategy

Fixing example buildpacks strategy by applying elevated privileges on
the steps it needs to read `/home/tekton/.docker` directory. And making
sure `-cache-dir` is used.

* Skipping Buildpacks Analyzer Step

It was failing on finding upstream image tag. For instance:

```
ERROR: failed to access previous image: connect to repo store 'quay.io/olemefer/nodejs-ex:cabal': TAG_EXPIRED: Tag cabal was deleted or has expired. To pull, revive via time machine; map[]
```

* Updating primary documentation.

* Updating buildpacks strategy documentation, removing analyzer.

* Typo.

* have a redhat-specific s2i strategy, minor readme changes

* rename all namespace references from sbose to build-examples

* rename all namespace references from sbose to build-examples

* update readme buildah example

Co-authored-by: Shoubhik Bose <sbose78@gmail.com>